name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Test on Ubuntu and Windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build g++

      - name: Configure CMake (Release mode)
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build build --config Release

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure -C Release
